name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '21.5.0'  # Keep Node.js version '21.5.0'

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        DP_FORCE_YTDL_MOD: ${{ secrets.DP_FORCE_YTDL_MOD }}


    - name: Start the bot
      run: npm start

    - name: Deploy
      run: |
        # Replace the following commands with your deployment script
        ssh root@146.190.162.178 'cd /root/HypeBot && git pull origin main && npm install && npm start'