name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '21.5.0'  # Keep Node.js version '21.5.0'

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables and start the bot
      run: |
        echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        echo "DP_FORCE_YTDL_MOD=${{ secrets.DP_FORCE_YTDL_MOD }}" >> $GITHUB_ENV
        node ./index.js

    - name: Deploy
      run: |
        # Replace the following commands with your deployment script
        ssh root@146.190.162.178 'cd /root/HypeBot && git pull origin main && npm install && node ./index.js'